name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-web-app .

      # Kiểm tra bảo mật với Trivy
      - name: Scan image with Trivy
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image my-web-app

      # Đăng nhập vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dongmt2}}
          password: ${{ secrets.nvdong111 }}

      # Tag và đẩy image lên Docker Hub
      - name: Push image to Docker Hub
        run: |
          docker tag my-web-app dongmt2/my-web-app:latest
          docker push dongmt2/my-web-app:latest
