name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-web-app .

      # Cài đặt linkchecker để test ứng dụng web
      - name: Install linkchecker
        run: sudo apt-get install -y linkchecker

      # Test ứng dụng web với linkchecker
      - name: Test web app with linkchecker
        id: web-test
        run: |
          docker run -d -p 8080:80 my-web-app
          linkchecker http://localhost:8080 --check-extern
        continue-on-error: true

      - name: Scan image with Trivy
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image my-web-app
          echo "scan_result<<EOF" >> $GITHUB_OUTPUT
          cat trivy_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        continue-on-error: true
      
      # Gửi thông báo đến Slack
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "Pipeline result:\nWeb test: ${{ steps.web-test.outcome }}\nTrivy scan: ${{ steps.trivy-scan.outcome }}\nTrivy errors:\n${{ steps.trivy-scan.outputs.scan_result }}\n${{ (steps.web-test.outcome == 'success' && steps.trivy-scan.outcome == 'success') && 'Proceeding to push image.' || 'Stopping pipeline due to errors.' }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # Login vào Docker Hub (chỉ nếu không có lỗi)
      - name: Login to Docker Hub
        if: steps.web-test.outcome == 'success' && steps.trivy-scan.outcome == 'success'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Đẩy image lên Docker Hub (chỉ nếu không có lỗi)
      - name: Push image to Docker Hub
        if: steps.web-test.outcome == 'success' && steps.trivy-scan.outcome == 'success'
        run: |
          docker tag my-web-app dongmt2/my-web-app:latest
          docker push dongmt2/my-web-app:latest
